### ISSUE TITLE
broadcast

### ISSUE THREAD

**Issue by alienatorZ** [ipfs-shipyard/ipfs-pubsub-room#1]
Hello, 
Nice work! While trying it out I only seem to be able to see my own broadcast messages. If another peer broadcasts only he sees it. Am I doing something wrong??

Here is my code:
```
    const room = Room(ipfs, 'presence')

			room.on('message',function(msg){
				console.log(msg.data.toString());
			});
			room.broadcast('hmmph!');
			//room.sendTo('QmcAmvDo7wwSxsP3DJYZuJpZqps7nUUcHUvn8r5SMUvBgf', "{}");

			room.on('peer joined',function(peer){
				console.log(peer + ' joined');
			});
			room.on('peer left',function(peer){
				console.log(peer + ' left');
			});
```

**Comment by haadcode** [comment]
@alienatorZ, as mentioned in https://github.com/ipfs-shipyard/ipfs-pubsub-room/issues/2#issuecomment-349928899, try with the latest version and let us know if you still have the problem. Would be happy to help fix it if your problem still exists!

**Comment by niinpatel** [comment]
I'm having the exact same issue and I'm using the latest version of ipfs-pubsub-room.
