### ISSUE TITLE
Tests should use a "on the fly Signalling Server" and not the hosted one

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/ipfs-pubsub-room#10]
Saw that running tests is running against the hosted node. 

```
Chrome 60.0.3112 (Mac OS X 10.12.6) LOG: 'Swarm listening on', '/libp2p-webrtc-star/dns4/star-signal.cloud.ipfs.team/wss/ipfs/QmZTkjJoH9Q2Qm7en8V5LtsWjzEJuGuKsLb2xQXE4Pb921'
Chrome 60.0.3112 (Mac OS X 10.12.6) LOG: 'Swarm listening on', '/libp2p-webrtc-star/dns4/star-signal.cloud.ipfs.team/wss/ipfs/QmTzYhkM3XpRZAwRipJjcFZyAiGUjAwhHQkCXFyDUeBtbU'
```

This opens the possibility to have failures by external forces that are not controlled by tests.

**Comment by eolszewski** [comment]
@diasdavid do you know of a repository that you can point at that currently does this?

**Comment by eolszewski** [comment]
Ah, here's something - https://github.com/diasdavid/webrtc-ring-signaling-server

**Comment by diasdavid** [comment]
@eolszewski you can check on js-libp2p tests itself -- https://github.com/libp2p/js-libp2p/blob/master/.aegir.js
