### ISSUE TITLE
Uncaught Error: no protocol with name: p2p-webrtc-star

### ISSUE THREAD

**Issue by jonnycrunch** [ipfs-shipyard/ipfs-pubsub-room#12]
protocols-table.js:17 Uncaught Error: no protocol with name: p2p-webrtc-star

**Comment by josselinchevalay** [comment]
hi jonycrunch, 

could you share your code and spécify wich version ipfs use and this library. 

regards

**Comment by pgte** [comment]
Yes, this is an issue, but on your IPFS node config. Please track this issue here: https://github.com/ipfs/js-ipfs/issues/1029
