### ISSUE TITLE
does not work on IPFS 0.26

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/ipfs-pubsub-room#13]

**Comment by josselinchevalay** [comment]
hi pgte, 

any error logs message ? maybe it can caused by https://github.com/ipfs-shipyard/ipfs-pubsub-room/blob/f548391185a703d6eeac10f554d826c9ae857f01/src/connection.js#L86

regards

**Comment by pgte** [comment]
Should be fixed by e19cc8cac360fc08db245ab007ae334a6008e9f9
