### ISSUE TITLE
'message' event should contain 'topicCIDs' array when emitted from _handleDirectConnection()

### ISSUE THREAD

**Issue by haadcode** [ipfs-shipyard/ipfs-pubsub-room#16]
Hey, I started looking into if we can use this module in orbit-db to achieve what @diasdavid suggested some time ago, to handle the "send first message automatically upon connecting to a peer" (it seems we can! :tada: :heart:)

In orbit-db's pubsub wrapper, we're relying on the `topicCIDs` array that is part of the message that is received from pubsub. And it's present in the messages ipfs-pubsub-room emits when messages are received as a "broadcast" but not when they're sent directly to a peer with `sendTo()`.

I took a look at the code and it looks to me that this is the place where we're missing the the `topicCIDs` array: https://github.com/ipfs-shipyard/ipfs-pubsub-room/blob/master/src/index.js#L138. Ie. to fix it, we should add `topicCIDs: [ this._topic ]` on line 141:
```js
pull.map((message) => {
  this.emit('message', {
    from: peerId,
    data: message,
    topicCIDs: [ this._topic ]
  })
  return message
}),
```

I started to write a PR, but unfortunately the [tests are not running](https://github.com/ipfs-shipyard/ipfs-pubsub-room/issues/17). I'd be happy to PR the fix.

Would you agree this is the right fix? Did I miss anything?

@pgte I love how this module exposes the 'peer joined' and 'peer left' events as well as gives us direct access to send a message to a specific peer. Thank you for writing it! :heart:

**Comment by pgte** [comment]
Hi @haadcode, I agree in general, but for me the topic can be a CID or any arbitrary string, so I would prefer emitting `{ from, data, topic }`. Would that be ok for you?

**Comment by haadcode** [comment]
@pgte I'm fine with it being whatever data type. 

What  I guess I would prefer is that the message shapes match between "broadcast" and "private" message, ie. to match what we return normally in pubsub. I believe this is the shape we have used so far: https://github.com/libp2p/js-libp2p-floodsub/blob/master/src/index.js#L276. Not sure why it is the way it is, and your comments brings up a good point that does it really need to be an array? We're also missing the `seqno` in the private message atm, I just noticed. 

So I suppose the question that needs to be answered is, if there's a reason the messages should look different between pubsub and room or should we follow the current pubsub message format? Again, I'm fine either way but would love to have coherent message format :)

**Comment by pgte** [comment]
@haadcode, that's a great point, I agree, the messages should be the same, and we should not change the type coming from pubsub. 👍

**Comment by haadcode** [comment]
Cool, ok, so the fix should then be to add [here](https://github.com/ipfs-shipyard/ipfs-pubsub-room/blob/master/src/index.js#L138):
- add `topicCIDs`(array) to the direct messages 
- add `seqno` (Buffer) to the direct messages

@pgte correct? Are there other places that need the same fix?

**Comment by pgte** [comment]
Correct. I don't see anywhere else that needs this..
