### ISSUE TITLE
Testing with js-ipfs next (0.28)

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/ipfs-pubsub-room#29]
Ran tests and got: 

<img width="746" alt="image" src="https://user-images.githubusercontent.com/1211152/36791491-086dcbde-1c66-11e8-9047-f7691bd78d91.png">

To prepare this module for the next release, you'll need:

- [ ] replace the `dial(peer, protocol, callback)` calls by `dialProtocol(peer, protocol, callback)`. See the updated libp2p API https://github.com/libp2p/js-libp2p#api

**Comment by AquiGorka** [comment]
This is what I addressed here: https://github.com/ipfs-shipyard/ipfs-pubsub-room/pull/31

**Comment by diasdavid** [comment]
thank you @AquiGorka :)
