### ISSUE TITLE
how am i sure my node is really connected

### ISSUE THREAD

**Issue by josselinchevalay** [ipfs-shipyard/ipfs-pubsub-room#3]
Hi i attempt to use that but i have weird behavior.

``` 
let room = Room(node, "test")
console.log(room.getPeers()) // [] ever if i have already run a another node
```

but i create a little server to this code return list of peerId 

i don't understand

Regards

**Comment by josselinchevalay** [comment]
really connected i'm not sure is possible but i can sure my program subscribe channel on pubsub with that
```
room.once('subscrided', () => {
    console.log('subscribe my channel on pubsub');
})
```
maybe is sufficent @pgte

**Comment by pgte** [comment]
You can do that by listening to events on your IPFS node. (check [the IPFS docs](https://github.com/ipfs/js-ipfs#readme))

Also, when you get a new peer (`peer joined` event), you know you're connected to that peer.

Please reopen this is this is not sufficient.
