### ISSUE TITLE
'suspicious' npm release

### ISSUE THREAD

**Issue by isaackwan** [ipfs-shipyard/ipfs-pubsub-room#40]
I noticed that there is a v1.2.1 release on [npm](https://www.npmjs.com/package/ipfs-pubsub-room)... but it's not published as release and tagged here. Any insights in what has changed?

**Comment by pgte** [comment]
@isaackwan sorry, forgot to push the tags. Should be ok now.
The fix was this one: https://github.com/ipfs-shipyard/ipfs-pubsub-room/pull/39
