### ISSUE TITLE
preparations for js-ipfs 0.29.0

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/ipfs-pubsub-room#43]
I've run the tests of this module in preparation for https://github.com/ipfs/js-ipfs/issues/1320.

All of the tests pass, however, note that the PubSub API did change, consider updating carefully.

**Comment by alanshaw** [comment]
WRT the change to `pubsub.subscribe` this module won't be affected as it does not use the `options` object.

With `pubsub.unsubscribe` becoming async, some refactoring will need to take place because when "leave" is called, the room won't be fully unsubscribed when the "stop" event is fired.

**Comment by pgte** [comment]
@alanshaw thanks!

Support for this landed on v1.3.0.
