### ISSUE TITLE
how to use localhost libp2p-websocket?

### ISSUE THREAD

**Issue by maroodb** [ipfs-shipyard/ipfs-pubsub-room#45]
I run my own  libp2p-websocket-star signalling-server with this address:  **/ip6/127.0.0.1/tcp/9090/ws/p2p-websocket-star/**

how to use this address as a swarm ?

**Comment by maroodb** [comment]
It works when I made:
 Swarm: [
                '/dns4/127.0.0.1/tcp/9090/ws/p2p-websocket-star/'
            ]

**Comment by pgte** [comment]
Looks like you have it, but here it is anyway, referring to the js-ipfs documentation:
https://github.com/ipfs/js-ipfs#is-there-a-more-stable-alternative-to-webrtc-star-that-offers-a-similar-functionality
