### ISSUE TITLE
what is the identifier of a room in the network ?

### ISSUE THREAD

**Issue by maroodb** [ipfs-shipyard/ipfs-pubsub-room#46]
is the room name the unique identity of a room ?
what if there is many rooms using the same name?

**Comment by pgte** [comment]
Yes, it's a unique identity. It's the name of the pub-sub channel, to be shared with any one also listening.

**Comment by maroodb** [comment]
what about if others create a room with the some name?

**Comment by pgte** [comment]
They share the room then.

**Comment by maroodb** [comment]
And how long room exists? until the leave of the last peer?
I want to create a create a permanent room , is that possible?

**Comment by pgte** [comment]
There's no centralised notion of a room. The notion is only local. Peers o the same room will eventually learn about each other using the IPFS discovery mechanisms..
