### ISSUE TITLE
Push 0.1.4 to NPM

### ISSUE THREAD

**Issue by lgierth** [ipfs-shipyard/ipfs-pubsub-room#5]
Seems that was forgotten

**Comment by unibitlabs** [comment]
[https://pastebin.com/k7Evffj5](url) This is the error in question when attempting to run shared-editing-demo; thanks for the fix.

**Comment by diasdavid** [comment]
I believe this is a dup of https://github.com/ipfs/js-ipfs/issues/944, but yeah it seems 0.1.4 needs to be published too :)

**Comment by pgte** [comment]
Published.
