### ISSUE TITLE
Error on npm install ipfs-pubsub-room

### ISSUE THREAD

**Issue by lauradew** [ipfs-shipyard/ipfs-pubsub-room#55]
I'm getting the following error when I try to install:
```
$ npm install -S ipfs-pubsub-room
npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t ssh://git@github.com/haadcode/ipfs-pubsub-room.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lauradewitt/.npm/_logs/2018-08-03T21_07_40_526Z-debug.log
```

anyone else encounter this? I also see the same with `npm i git+https://git@github.com/ipfs-shipyard/ipfs-pubsub-room.git`

**Comment by pgte** [comment]
Hi Laura,

Looks like your local package.json may have a GitHub URL.
You should be installing via NPM and not use a GitHub URL.

**Comment by lauradew** [comment]
Hi Pedro,
I had been trying to install via NPM but my node_modules/orbit-db-pubsub/package.json had the github url as a dependency. Removed that and works great, thanks!
