### ISSUE TITLE
Direct p2p messages.

### ISSUE THREAD

**Issue by klueq** [ipfs-shipyard/ipfs-pubsub-room#59]
I see this app can send messages directly to a chosen peer. That's pretty cool, as I was looking for a way to do this.

How efficient is this method compared to sending a UDP message to that peer? Does this method broadcast anything or actually sends the message directly to the peer? If we group all the IPFS nodes into pairs and let one node send a p2p message to the other node, will it cause any troubles?

**Comment by pgte** [comment]
This method uses a direct connection to that peer, which uses the underlying libp2p transport, which may be any of the configured ones, like TCP, Websockets, WebRTC, etc.

If you're thinking of using UDP for unreliable pubsub, I think that IPFS does not support that, but you can pose that question directly to ipfs/ipfs (or ipfs/js-ipfs).

Right now, the broadcast topology is floodsub, which is pretty suboptimal. Experiments with gossip topologies like Epidemic Broadcast Trees and similar have happened, but not included in IPFS or libp2p. Again, for this you should post to IPFS or libp2p :)

**Comment by klueq** [comment]
Thanks a lot for quick reply!
